Lesson 3
VladimirMinka/KotlinSprint pull request #3
Opened 2022-12-27 12:25 UTC by VladimirMinka

2022-12-28 06:40 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_1.kt
> +    println("$privet $timeToEvening $name")
В такой реализации будут выводиться лишние символы пробелов между словами. В println уже учитываются пробелы при интерполяции, дополнительные отступы в объявлении переменных не нужны

2022-12-28 06:45 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_1.kt
> +    println("$privet $timeToEvening $name")
Запятую не нужно использовать в объявлении переменных. Все это должно быть в конечной сформированной строке. 
В переменных хранятся только значения. Достаточно объявить два приветствия "Добрый день" и "Добрый вечер". "Добрый" - не может существовать отдельно, потому, что не может универсально использоваться, например, если будет введен новый тип приветствия "Доброй ночи".

2022-12-28 06:47 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +    val lastSureName = "Сидорова "
Тут тоже лишние пробелы
И я бы отбивал пустой строкой (здесь и далее) блок с объявлением переменных от блока с остальным кодом

2022-12-28 06:51 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_3.kt
> +    val number = 5
А что будет, если здесь проинициализировать переменную другим числом? Нужна доработка

2022-12-28 06:55 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
> +    println("Ваш ход: $firstMotion-$secondMotion, ход - $numberMotion")
Не соблюдены условия задачи: формат вывода должен быть строго по тз (сервер умеет читать только его), пешка продвинулась на одну клетку

2022-12-28 07:02 UTC, ievetrov commented on src/main/kotlin/lesson_3/lesson_3_task_5.kt
> +    val resultMotion = ("$firstMotion-$secondMotion,$numberMotion")
Лишние круглые скобки и неточность в формате (по тз разделитель ;)
Но опять же согласно тз, достаточно было объявить строку "D2-D4;0"
По решению ниже все ок

2022-12-28 07:03 UTC, ievetrov requested changes
Нужны некоторые доработки, поставил в статус Request changes

2023-01-10 07:02 UTC, VladimirMinka commented on src/main/kotlin/lesson_3/lesson_3_task_1.kt
> +    println("$privet $timeToEvening $name")
Поправил код с учетом замечаний

2023-01-10 07:03 UTC, VladimirMinka commented on src/main/kotlin/lesson_3/lesson_3_task_2.kt
> +    val lastSureName = "Сидорова "
отрефакторил код с учетом замечаний

2023-01-10 07:23 UTC, VladimirMinka commented on src/main/kotlin/lesson_3/lesson_3_task_3.kt
> +    val number = 5
код отрефакторил так чтобы значение  подставлялись из ранее объявленной переменной и вычислялись при выводе на экран

2023-01-10 07:55 UTC, VladimirMinka commented on src/main/kotlin/lesson_3/lesson_3_task_4.kt
> +    println("Ваш ход: $firstMotion-$secondMotion, ход - $numberMotion")
Добавил []  при выводе в консоль

2023-01-31 09:22 UTC, VladimirMinka commented
-

2023-01-31 09:22 UTC, closed without merging

2023-01-31 09:22 UTC, VladimirMinka commented
-